USE `rejik`;

STOP SLAVE; 
RESET MASTER;
RESET SLAVE;


TRUNCATE TABLE `banlists`;
TRUNCATE TABLE `checker`;
TRUNCATE TABLE `log`;
TRUNCATE TABLE `servers`;
TRUNCATE TABLE `urls`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `users_acl`;
TRUNCATE TABLE `users_linked`;
-- TRUNCATE TABLE `variables`;

-- START SLAVE;

SHOW SLAVE STATUS;